# Generated by Django 3.0.5 on 2020-04-22 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apitest',
            name='Apitest',
        ),
        migrations.AddField(
            model_name='apitest',
            name='Product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
